DjangoApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('give10/', include('give10.urls')),
    path('', RedirectView.as_view(url='give10/')),
    path('accounts/', include('django.contrib.auth.urls'))
]

give10/urls.py
from django.urls import path
from .views import index, SignUpView, ViewByUser, ViewAll, TipCreate
from .views import TipDetail, TiptypeCreate, TipDeleteView, TipUpdate, SearchView

app_name = 'give10'

urlpatterns = [
    path('', index, name='index'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/', ViewByUser.as_view(), name='profile'),
    path('alltips/', ViewAll.as_view(), name='all_tips'),
    path('results/', SearchView.as_view(), name='search'),
    path('new_tiptype/', TiptypeCreate.as_view(), name='new_tiptype'),
    path('new_tip/', TipCreate.as_view(), name='new_tip'),
    path('tip/<int:pk>/', TipDetail.as_view(), name='tip_detail'),
    path('tip/<int:pk>/delete/', TipDeleteView.as_view(), name='tip_delete'),
    path('tip/<int:pk>/update/', TipUpdate.as_view(), name='tip_update'),
]

give10/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

class Tiptype(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class Tip(models.Model):
    title = models.CharField(max_length=150)
    tiptype = models.ForeignKey('Tiptype', on_delete=models.SET_NULL, null=True)
    why_10 = models.TextField(max_length=600)
    more_information = models.TextField(max_length=600)
    tip_date = models.DateField(null=True, blank=True)
    tip_giver = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    link = models.URLField(null=True, blank=True)

    class Meta:
        ordering = ['tip_date']

    def __str__(self):
        return f'{self.title} ({self.tiptype})'

    def get_absolute_url(self):
        return reverse("tip_detail", kwargs={"pk":self.pk})

give10/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponse
from .models import Tip, Tiptype
from django.views.generic import CreateView, DetailView, ListView, DeleteView, UpdateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from datetime import date

# Create your views here.

def index(request):
    num_tips = Tip.objects.all().count()
    num_users = User.objects.all().count()

    context = {
        'num_tips':num_tips,
        'num_users':num_users,
    }

    return render(request, 'give10/index.html', context=context)


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('give10:index')
    template_name = 'give10/signup.html'


class ViewByUser(LoginRequiredMixin, ListView):
    model = Tip
    template_name = 'give10/profile.html'
    paginate_by = 5

    def get_queryset(self):
        return Tip.objects.filter(tip_giver = self.request.user).all()

class ViewAll(LoginRequiredMixin, ListView):
    model = Tip
    template_name = 'give10/alltips.html'
    paginate_by = 5

    def get_queryset(self):
        return Tip.objects.all()

class SearchView(ListView):
    model = Tip
    template_name = 'give10/search.html'
    context_object_name = 'all_search_results'

    def get_queryset(self):
        result = super(SearchView, self).get_queryset()
        query = self.request.GET.get('search')
        if query:
            postresult = Tip.objects.filter(title__contains=query) | Tip.objects.filter(tiptype__name__contains=query) | Tip.objects.filter(tip_giver__username__contains=query)
            result = postresult
        else:
            result = None
        return result


class TiptypeCreate(LoginRequiredMixin, CreateView):
    model = Tiptype
    fields = '__all__'
    success_url = reverse_lazy('give10:index')

class TipCreate(LoginRequiredMixin, CreateView):
    model = Tip
    fields = ['title','tiptype','why_10','more_information','link']
    success_url = reverse_lazy('give10:index')

    def form_valid(self, form):
        form.instance.tip_giver = self.request.user
        form.instance.tip_date = date.today()
        return super().form_valid(form)

class TipUpdate(LoginRequiredMixin, UpdateView):
    model = Tip
    fields = ['title','tiptype','why_10','more_information','tip_date','link']
    success_url = reverse_lazy('give10:index')

    def form_valid(self, form):
        form.instance.tip_giver = self.request.user
        return super().form_valid(form)

class TipDeleteView(LoginRequiredMixin, DeleteView):
    model = Tip
    success_url = reverse_lazy('give10:index')

class TipDetail(LoginRequiredMixin, DetailView):
    model = Tip

DjangoApp/templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'give10/custom.css' %}">

    <title>Document</title>
</head>
<body>
    
    <nav class="navbar navbar-expand-sm bg-light">
        <div class="container-fluid">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'give10:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'give10:profile' %}">My Tips</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'give10:new_tip' %}">New Tip</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'give10:new_tiptype' %}">New Tip Type</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'give10:signup' %}">New User</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'give10:all_tips' %}">See All Tips</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'give10:search' %}">Search Tips</a>
              </li>
            </ul>
        </div>
    </nav>


    {% block content %}

    {% endblock %}

</body>
</html>

give10/templates/give10/alltips.html
{% extends 'base.html' %}

{% block content %}

<h1>Welcome to our tips list!</h1>

<h2>Here are the tips we received so far:</h2>

<ul>
    {% for tip in tip_list %}
    <li>
        <a href="{% url 'give10:tip_detail' tip.pk %}">{{tip}} - {{tip.tip_giver}}</a>
        <br>
    </li>
    {% endfor %}
</ul>

{% endblock %}

give10/templates/give10/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>Welcome to GIVE 10!</h1>

<h2>Just read an incredible book? Got back from an amazing place? Did a super useful course?</h2>

<h2>We want to get some great tips from you (for any kind of think you want).</h2>

<h2>We will share it with the whole world, so fell free to get some nice tips back as well.</h2>


<img src="{% static 'give10/asterix.gif' %}" alt="My image">
    

<p>Total Tips Already Received: {{num_tips}} </p>
<p>Users Already Giving tips: {{num_users}} </p>

    {% if user.is_authenticated %}
        <p>You are Logged In</p>
        <p>Welcome: {{user.get_username}}</p>
        <a href="{% url 'logout' %}?next={{request.path}}">Logout</a>
    {% else %}
        <p>You are not logged in</p>
        <a href="{% url 'login' %}?next={{request.path}}">Login</a>
    {% endif %}

{% endblock %}


    

    

give10/templates/give10/profile.html
{% extends 'base.html' %}

{% block content %}

<h1>Welcome to your tips list!</h1>

<h2>Here are the tips you gave us already:</h2>

<ul>
    {% for tip in tip_list %}
    <li>
        <a href="{% url 'give10:tip_detail' tip.pk %}">{{tip}}</a>
        <br>
    </li>
    {% endfor %}
</ul>

{% endblock %}

give10/templates/give10/search.html
{% extends 'base.html' %}

{% block content %}

<h1>Welcome to our search tips engine!</h1>
<br>
<h2>You can search by Tip Title, Tip Type and Tip Giver!</h2>
<br>

<form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'give10:search' %}" >
            <input class="form-control mr-sm-2" type="search" name="search">
            <button class="btn btn btn-outline-info my-2 my-sm-0" type="submit"> Search </button>
</form>

<h2>Here are the tip results of your search:</h2>

<ul>
    {% for tip in all_search_results %}
    <li>
        <a href="{% url 'give10:tip_detail' tip.pk %}">{{tip}} - {{tip.tip_giver}}</a>
        <br>
    </li>
    {% empty %}
        <h2>No results found</h2>
    {% endfor %}
</ul>

{% endblock %}

give10/templates/give10/signup.html
{% extends 'base.html' %}

{% block content %}

<h1>Register New User Here</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="signup">

</form>

{% endblock %}

give10/templates/give10/tip_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h1>Tip Delete</h1>
    <h2>Do you really want to delete this tip?</h2>
        {% csrf_token %}
        <div class="form-group">
        <h2>Tip title: {{tip.title}}</h2>
        <form class="wide" action="." method="post">
            {% csrf_token %}
            <p class="submit">
                <input class="cta" type="submit" value="Yes, delete the tip.">
            </p>
          </form>
</div>

{% endblock %}

give10/templates/give10/tip_detail.html
{% extends 'base.html' %}

{% block content %}

<h1>Tip Details</h1>
<div>{{tip.title}}</div><br>
<div>{{tip.tiptype}}</div><br>
<div>{{tip.why_10}}</div><br>
<div>{{tip.more_information}}</div><br>
<div>{{tip.tip_date}}</div><br>
<div>{{tip.tip_giver}}</div><br>
<div>{{tip.link}}</div><br>
<br>
{% if tip.tip_giver == request.user %}
<a href="{% url 'give10:tip_update' tip.pk %}">Update Tip</a>
<br>
<a href="{% url 'give10:tip_delete' tip.pk %}">Delete Tip</a>
{% endif %}
{% endblock %}

give10/templates/give10/tip_form.html
{% extends 'base.html' %}

{% block content %}

<h1>Create new Tip</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="CREATE">
</form>

{% endblock %}

give10/templates/give10/tiptype_form.html
{% extends 'base.html' %}

{% block content %}

<h1>Create new Tip Type</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="CREATE">
</form>

{% endblock %}